
version: "3"

services:
  test:
    image: node:15
    ports:
      - "8080:8080"
    environment:
      LANG: ja_JP.UTF-8
      TZ: Asia/Tokyo
    volumes:
      - ./frontend:/app
    container_name: test_app
    command: ["sleep", "infinity"]

